# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: sudo|butt|buddies|69
      MARIADB_USER: sqlUser
      MARIADB_PASSWORD: Passw0rd!
      MARIADB_DATABASE: client_schedule
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql